### ISSUE TITLE
Update UWP/Xamarin versions

### ISSUE THREAD

**Issue by ghost** [nunit/nunit-vs-templates#22]
I have VS 2015 Enterprise running on Win 10 Ent Ann Edition.

When I attempt to add the NUnit Universal Test Project I get the below dialog.

---
## OK   

I selected Window Build 10568 for both target and min version.

I created this project from scratch using the same selections.

But, the NuGet Template won't let me create the test project using the same settings.

Can you correct this?

Thanks

Karl

**Comment by magnuand** [comment]
I'm getting the same error.

**Comment by ChrisMaddock** [comment]
@rprouse - Both this and nunit.xamarin target UWP 10240, the first version. It looks like we can specify different target versions and min version, should we upgrade the target version? We'd probably want to force the CI to run against 10240, to check backwards-compatibility, whilst allowing things to work with the latest 14393...

See the last section of this page for info. https://msdn.microsoft.com/en-gb/windows/uwp/updates-and-versions/choose-a-uwp-version

**Comment by rprouse** [comment]
@ChrisMaddock yes we should probably update to the latest version. We also need to update the Xamarin project to use newer versions of Xamarin.Forms and update the templates accordingly.

**Comment by ChrisMaddock** [comment]
Blocked by nunit/nunit.xamarin#65, pending a new nunit.xamarin release.

**Comment by ChrisMaddock** [comment]
Reminder: within this also update the templates to no longer use the old `nunit.AutoRun`.

**Comment by ChrisMaddock** [comment]
Also note https://github.com/nunit/nunit.xamarin/pull/77 for the UWP runner template
