### ISSUE TITLE
Code snippets not available

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-vs-templates#23]
I don't seem to be able to get the NUnit code snippets to show up in VS 2015. Possibly related, I see two "Test" entries, both of which produce MSTests snippets. I wonder if there's a naming collision.

![image](https://cloud.githubusercontent.com/assets/4837132/19804598/36f8279a-9d07-11e6-970e-a8a03c08dd76.png)

Originally from: https://visualstudiogallery.msdn.microsoft.com/6cd55f79-4936-49e7-b81d-c40fcd81abc7

**Comment by ChrisMaddock** [comment]
Looks like it is a naming collision.

We define our snippets to live in a dir named "Test". If I manually rename that to "NUnit", the problems resolved.

I guess we should work around that, but it seems like a VS bug. @rprouse - do we have any particular channel to raise that?

**Comment by ChrisMaddock** [comment]
Interestingly, VS's Code Snippets Manager detects that 'something' is wrong with the `Test` dir, but doesn't provide any error message, and then continues to display it incorrectly in the snippets context menu. 

![image](https://cloud.githubusercontent.com/assets/4837132/19806463/074ebbf6-9d13-11e6-9ab6-ff3f6d2b8900.png)

**Comment by ChrisMaddock** [comment]
@rprouse - I've rejigged the 1.3 milestone, is that ok? If I tidy up here, could we do another release after the nunit.xamarin release?

I had a wee dig to see if there's anyway to remove the dependencies on specific package versions for the nunit projects - unfortunately it doesn't seem so without some dirty hacks. I think it would be good if we could try and release this in sync with the framework (and nunit.xamarin, when required) - I may have a look at some automation to make that simpler.

**Comment by rprouse** [comment]
I think switching the folder that the snippets are stored in to NUnit is a good idea. It will ensure that there are no conflicts. The weird thing is, they work for me in VS2015, I use them all the time.

Feel free to rejig milestones and start planning a release. I keep meaning to get back to this project, but keep getting distracted by the framework and console issues.

**Comment by ChrisMaddock** [comment]
That's odd! I've never used MSTest, so wouldn't have installed anything specific...maybe it's an optional feature?

This is the "colliding" snippet set, do you have this available? If so, I wonder if it's based on installation order or something...

![image](https://cloud.githubusercontent.com/assets/4837132/19814673/25e4a52a-9d37-11e6-9dee-d4f52353fcb6.png)
