### ISSUE TITLE
Projects should be created as test projects

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-vs-templates#24]
Originally from: https://visualstudiogallery.msdn.microsoft.com/6cd55f79-4936-49e7-b81d-c40fcd81abc7/view/Discussions

> ProjectTypeGuids-Tag is missing in the generated csproj leading to 'wrong' project icon in the solution explorer.
> Please add `<ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB}</ProjectTypeGuids>` to the generated Test-Project.

The guid is the VS test project guid. As well as the 'right icon' - creating them as test projects also means they can be picked up straight away by test adapters, without needing an additional edit to the csproj, I believe.

**Comment by rprouse** [comment]
We need to think about this one. Last time I tried it, test projects didn't work in MonoDevelop. We prefer everything we do to be cross platform, but this project is intended for Visual Studio. I am just worried about people creating projects in Visual Studio and them not working in Mono.

Anyone have thoughts on this?

**Comment by ChrisMaddock** [comment]
Interesting - I would have thought MonoDevelop would have ignored just the `ProjectTypeGuid` if it didn't understand it. 

If that's still the case, I think it's reasonable grounds to close this issue - I just saw it as a nicety.

**Comment by ChrisMaddock** [comment]
In fact, I'm going to go ahead and close this. The original comment is already a few months old, and it's mainly an minor aesthetic issue. If someone was interested enough to PR and put the work in to check things out with MonoDevelop that would be great, but I don't think it's enough of a concern to keep an open issue for.

Thanks for the insight, @rprouse. 😄
