### ISSUE TITLE
Update to VSIX format v3 for VS 2017

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-vs-templates#27]
We should also use the bigger logo at the same time.

**Comment by rprouse** [comment]
For the icon, see comments about the sizes at nunit/nunit3-vs-adapter#268

**Comment by ChrisMaddock** [comment]
@OsirisTerje @rprouse - I've had a go at this, but it seems a little buggy, wondered if either of you could shed any light after doing the other extensions?

My extension project gets as far as building the VSIX, but then the build fails to launch the experimental instance with: 

    error VSSDK1081: Problem occurred while extracting the vsix to the experimental extensions path.

If I manually run the VSIX, it installs in a disabled state. I can then enable it and things seem to work ok - but at this point I'm not sure if it's a problem with the VSIX, or my VS15 install. 😕 

Did either of you come across anything like this doing the other projects, or was it all fairly clean cut? I've pushed what I've done as [issue-27](https://github.com/nunit/nunit-vs-templates/compare/issue-27?expand=1) - if either of you would have a chance to try it out.

**Comment by ChrisMaddock** [comment]
(I should maybe add that I couldn't build any of the VSIXv3's we currently have, so the likelihood of my installation having a problem is maybe high...)

**Comment by OsirisTerje** [comment]
I did have issues with my laptop, I could build the vsix, but not install it, the one I built worked for others though.  On my workstation, everything seems to work fine.  So, there might be some issues with VS too here, side-by-side, pre-beta releases or whatever.  Try to see if you can make it work on a clean VM.

**Comment by OsirisTerje** [comment]
I'll try your vsix tomorrow :-)

**Comment by rprouse** [comment]
Have you tried deleting your experimental instance? You will find it in `C:\Users\{user]\AppData\Local\Microsoft\VisualStudio`

**Comment by ChrisMaddock** [comment]
Thanks both. 😄 

@rprouse - good idea, hadn't thought of that. No joy though, unfortunately.

**Comment by RehanSaeed** [comment]
@ChrisMaddock Did you work out what's causing the `error VSSDK1081: Problem occurred while extracting the vsix to the experimental extensions path.` issue? I'm getting the same thing with one of my VSIX's. Here is a potential fix: https://github.com/Microsoft/visualfsharp/pull/1751

**Comment by ChrisMaddock** [comment]
@RehanSaeed - I planned to try again in a later RC and see if they fixed it, but afraid I never got back to it. The fix you posted looks promising though, thanks for that!

I don't have a VS2017 installation right now, ill have to redownload and try again.

**Comment by ChrisMaddock** [comment]
@RehanSaeed - turns out my issue was https://github.com/Microsoft/extendvs/issues/41 - which I found via your post at https://github.com/ligershark/template-builder/issues/96#issuecomment-289825539.

Thanks for sharing the outcome of your struggles - now finally got it up and running!

**Comment by RehanSaeed** [comment]
Glad you got it sorted. Was a nasty bug!
