### ISSUE TITLE
Can't create a UWP test project

### ISSUE THREAD

**Issue by robertrosman** [nunit/nunit-vs-templates#36]
Whenever I try to add a UWP test project to my solution I get the following error (freely translated from swedish).

> File not found (Exception from HRESULT: 0x80070002)

I had another error earlier, but I think it was related to installing the Windows 10 SDK, at least it disappeared after I installed the SDK. The previous message was complaining about TemplateWizard, can't remember exactly.

So I'm pretty stuck here. Can't start a new uwp test project and I can't find up to date information on how to start such a project from scratch. Any help or suggestions?

BTW I'm on VS 2017 Community and Win 10 Pro.

**Comment by ChrisMaddock** [comment]
I presume you don't get as far as this message?

![image](https://user-images.githubusercontent.com/4837132/27183825-f7c71b54-51d7-11e7-9ca3-468da4b5fca5.png)

Which UWP versions do you have installed? Is there any more in the error message than 'File not Found' - it doesn't specify which files are missing?

If there's nothing clear - you might be able to pull out more information in a Visual Studio log? I don't know how much the templating stuff will log...

https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/

**Comment by ChrisMaddock** [comment]
Hmm, do you by any chance only have the very latest UWP version installed? (15063?) Our UWP project is currently set up for versions 10586 - 14393. This used to give a nicer error message (see https://github.com/nunit/nunit-vs-templates/issues/22) - but things may have changed. If so - try installing an older UWP, and see if that fixes things?

If this is the problem - this could become a bit of a maintenance nightmare...

**Comment by ChrisMaddock** [comment]
To get round this for now, you could create the UWP test app manually, following the samples on this page: https://github.com/nunit/docs/wiki/Getting-Started-in-Visual-Studio

**Comment by robertrosman** [comment]
@ChrisMaddock thanks for your fast reply! As far as I can tell my installed version is 14393. I don't get to the "choose platform version dialog". Now I'm back with the old error message that says:

> Error: this template attempted to load component assembly 'Microsoft.VisualStudio.Universal.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates.

I'll see if I can find anything in the activity log. I tried to create the UWP test app manually but without success. I'm new to VS/c#/Windows development so this is a stumbling block at the moment.

**Comment by ChrisMaddock** [comment]
@roggan87 

Sounds like you might be missing a development component. This suggestion comes up across various sites:

> Run the visual studio installer again. Select "Modify" in the Installer. Select Features - "Windows and Web Development" - "Universal Windows App Development Tools" - Click Update / Install.

http://www.danievdm.org/index.php?view_det&post=10

**Comment by robertrosman** [comment]
Thanks for the feedback, I'll try to repair the installation. I've tried to modify it with the installer as mentioned in http://www.danievdm.org/index.php?view_det&post=10

I'll investigate it further and get back...

**Comment by ChrisMaddock** [comment]
@roggan87 Did you manage to get anywhere with this? 🙂

**Comment by robertrosman** [comment]
Sorry for not getting back. We've decided to let UWP wait a bit for our project, so I didn't bother reinstalling Visual Studio. Feel free to close this issue for now if you like.-------- Ursprungligt meddelande --------Ämne: Re: [nunit/nunit-vs-templates] Can't create a UWP test project (#36)Från: Chris Maddock Till: nunit/nunit-vs-templates Kopia: roggan87 ,Mention @roggan87 Did you manage to get anywhere with this? 🙂

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nunit/nunit-vs-templates","title":"nunit/nunit-vs-templates","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nunit/nunit-vs-templates"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ChrisMaddock in #36: @roggan87 Did you manage to get anywhere with this? 🙂 "}],"action":{"name":"View Issue","url":"https://github.com/nunit/nunit-vs-templates/issues/36#issuecomment-310667451"}}}

**Comment by ChrisMaddock** [comment]
No worries, thanks for letting us know. 👍

**Comment by xplicit** [comment]
Is there a project on github which shows sample of created NUnit UWP project? NUnit templates does not work for UWP in VS2017 and documentation here https://github.com/nunit/docs/wiki/Getting-Started-in-Visual-Studio is not clear enough. It shows parts of code which does not work together. it's not clear which references are required to be added, what is the original content of `App.xaml.cs` which should be modified.

**Comment by rprouse** [comment]
https://github.com/nunit/nunit.xamarin/tree/master/src/tests/nunit.runner.tests.uwp is an example project, although it might be a bit out of date.
