### ISSUE TITLE
Update templates for VS 2022

### ISSUE THREAD

**Issue by stephenjwalter** [nunit/nunit-vs-templates#55]
Is it possible to update this package for Visual Studio 2022?

**Comment by rprouse** [comment]
We could, but we haven't really been maintaining this project since NUnit templates are included by default in Visual Studio now. What part of this are you using, the snippets and/or file templates?

**Comment by stephenjwalter** [comment]
Oh, I hadn’t yet noticed the template inclusion. I use both templates and snippets. I’ll close this now and see where I am.
Thanks for the reply.

**Comment by rprouse** [comment]
We'd like to figure out a way to include or distribute the snippets. This project is pretty out of date though and doesn't work well in newer versions of VS. For now, I just create my own custom snippets.

**Comment by glen-nicol** [comment]
@rprouse can you confirm that the templates included with VS now are just project templates? I see those but do not see file templates (what used to be under the Test group when "Add New Item" was selected from solution explorer). 

Are the file templates snippets too? 
Can the snippet files be copied from this project into the snippet manager?

**Comment by rprouse** [comment]
The included templates are just project templates sorry. You might be able to copy the snippets in, sorry, I haven't tried.
